In [1]:
age_21 = True
print(age_21)
type(age_21)

True


bool

In [2]:
age_21 = True
print(age_21)
type(age_21)

True


bool

In [3]:
num1 = 1
num2 = 2
print(num1 , num2)

1 2


In [4]:
num3 = num1
num1 = num2
num2 = num3
print(num1 , num2)

2 1


In [5]:
a = 2
b = 3
c = a**b
print(c)


8


In [6]:
pie=3.14
r=4
circle=pie*r
print(circle)


12.56


In [7]:
p=10000
n=5
r=8
simple_interset=p*n*r/100
print(simple_interset)

4000.0


In [8]:
a=6
b=5
print(a+b)

11


In [9]:
a=6
b=5
a+=b
print(a)

11


In [10]:
print('hwllo everyone my name is aditya')

hwllo everyone my name is aditya


In [11]:
name='Aditya'
last_name='jadhav'
name+ " "+last_name

'Aditya jadhav'

In [12]:
print('hi everyone, my name is' ,name + ' ' + last_name)

hi everyone, my name is Aditya jadhav


In [13]:
last_name * 100

'jadhavjadhavjadhavjadhavjadhavjadhavjadhavjadhavjadhavjadhavjadhavjadhavjadhavjadhavjadhavjadhavjadhavjadhavjadhavjadhavjadhavjadhavjadhavjadhavjadhavjadhavjadhavjadhavjadhavjadhavjadhavjadhavjadhavjadhavjadhavjadhavjadhavjadhavjadhavjadhavjadhavjadhavjadhavjadhavjadhavjadhavjadhavjadhavjadhavjadhavjadhavjadhavjadhavjadhavjadhavjadhavjadhavjadhavjadhavjadhavjadhavjadhavjadhavjadhavjadhavjadhavjadhavjadhavjadhavjadhavjadhavjadhavjadhavjadhavjadhavjadhavjadhavjadhavjadhavjadhavjadhavjadhavjadhavjadhavjadhavjadhavjadhavjadhavjadhavjadhavjadhavjadhavjadhavjadhavjadhavjadhavjadhavjadhavjadhavjadhav'

In [14]:
a = '10,000000'
print(type(a))
id(a)

<class 'str'>


2413742030448

In [15]:
a = 1 , 2 ,2.3 , 2.4 , 'aditya' , True
print(a)
type(a)

(1, 2, 2.3, 2.4, 'aditya', True)


tuple

In [16]:
a * 3

(1,
 2,
 2.3,
 2.4,
 'aditya',
 True,
 1,
 2,
 2.3,
 2.4,
 'aditya',
 True,
 1,
 2,
 2.3,
 2.4,
 'aditya',
 True)

In [17]:
a = 'hello'
b = 'world!'
a+ "  " + b

'hello  world!'

In [18]:
a = 1 , 2 ,2.3 , 2.4 , 'aditya' , True
print(a)
type(a)


(1, 2, 2.3, 2.4, 'aditya', True)


tuple

In [19]:
a*3

(1,
 2,
 2.3,
 2.4,
 'aditya',
 True,
 1,
 2,
 2.3,
 2.4,
 'aditya',
 True,
 1,
 2,
 2.3,
 2.4,
 'aditya',
 True)

In [20]:
'aditya jadahv' in a

False

In [21]:
min(a)

TypeError: '<' not supported between instances of 'str' and 'int'

In [ ]:
a = "aditya jadhav"
print(a)
len(a)

aditya jadhav


13

In [ ]:
tuple1 = (1, 2, 3, 4, 5,100,300)
min(tuple1)

1

In [ ]:
a = 'python' 

tuple(a)

('p', 'y', 't', 'h', 'o', 'n')

In [ ]:
a[0]

'p'

In [ ]:
tup=(5,10,15,20,25)
tup[-2]

20

In [ ]:
a='hello  everyone'
a[-4:-1]

'yon'

In [ ]:
tup=(1,2,3,4,5)
tup[-1:5]

(5,)

In [ ]:
a = 'machinelearning'
a

'machinelearning'

In [ ]:
print(a[-10:-1])     

nelearnin


In [ ]:
a = 'machinelearning'
print(a[-8:])  

learning


In [ ]:
a= 'machine learning'
print(a[-8:])

learning


In [ ]:
a='python'
a[0:3]

'pyt'

In [ ]:
a = (1,2,3,4,5)
a

(1, 2, 3, 4, 5)

In [ ]:
a[-5:]

(1, 2, 3, 4, 5)

In [ ]:
a=(5,10,15,20,25,30)
print(a[4:6])

(25, 30)


In [ ]:
a = [1,2,[3,4],5,6]
a[2:3]

[[3, 4]]

In [ ]:
a = (1,3,5,7,9,11)
a

(1, 3, 5, 7, 9, 11)

In [ ]:
a[::2]

(1, 5, 9)

In [ ]:
a = 'ABCDEFGHIJ'
a

'ABCDEFGHIJ'

In [ ]:
a[0::2]

'ACEGI'

In [ ]:
name = "Aditya"
print( name)

Aditya


In [ ]:
num = int(input("Enter a number: "))
if num > 0:
    print("The number is positive.")
else:
    print("The number is not positive.")

The number is positive.


In [ ]:
num = 22
if num % 2 == 0:
    print(f"{num} is an even number.")
else:
    print(f"{num} is an odd number.")

22 is an even number.


In [ ]:
balance = 10000
withdeawl_amount = int(input("Enter amount to withdraw: "))
if withdeawl_amount <= balance:
    print('transection_successful')
    balance -= withdeawl_amount
    print(f"Remaining balance:",balance)
else:
        print('insufficient balance')
    

transection_successful
Remaining balance: 1000


In [ ]:
# Q.30. Write a code to convert a list of strings into a set.
my_list = ['a','b','c','d']
print(set(my_list))


{'d', 'a', 'b', 'c'}


In [ ]:
18 & 3
bin(18)
bin(3)


'0b11'

In [ ]:
bin(18) + bin(3)

'0b100100b11'

In [ ]:
n = 7
i = 1
while i < n :
    print(i)
    i = i + 1

1
2
3
4
5
6


In [ ]:
n = 7 
i = 1
while i < n :
    i = i + 1
    if i == 3:
        continue
    print(i)
else :
        print("this will be executed when the while is run sucessfully without any break")

2
4
5
6
7
this will be executed when the while is run sucessfully without any break


In [ ]:
list(range(0,10,5))

[0, 5]

In [ ]:
bool(0)

False

In [ ]:
int(10.06)

10

In [ ]:
a = [[1,2,3],[4,5,6]]
print(type (a))
print(a[0])
print(a[0][2])

<class 'list'>
[1, 2, 3]
3


In [ ]:
a = {'name' : 'Aditya', 'age' : 21 , 'city' : 'pune'}
print(type(a))
print(a['name'])
a['name'] = 'jadhav'

<class 'dict'>
Aditya


In [ ]:
A ='ADITYA'
B = 'JADHAV'
print(A +' '+B)

ADITYA JADHAV


In [ ]:
A ='ADITYA'
print(A[:-3])

ADI


In [ ]:
a = 'aditya jadhav'
print (a.upper())
print (a.lower())
print (a.title())
print (a.capitalize())
print (a.swapcase())

ADITYA JADHAV
aditya jadhav
Aditya Jadhav
Aditya jadhav
ADITYA JADHAV


In [ ]:
a = "name\tage\tgrade\naditya\t22\tA"
print(a)

name	age	grade
aditya	22	A


In [ ]:
list1 = ['orange','banana','orange']
list1.insert(2,'tomato')
print(list1)

['orange', 'banana', 'tomato', 'orange']


In [ ]:
list1 = ['orange','banana','orange']
list2 = ['tomato','potato']
list1.extend(list2)
print(list1)

['orange', 'banana', 'orange', 'tomato', 'potato']


In [ ]:
list1 = ['orange','banana','orange']
print(list1*5)

['orange', 'banana', 'orange', 'orange', 'banana', 'orange', 'orange', 'banana', 'orange', 'orange', 'banana', 'orange', 'orange', 'banana', 'orange']


In [ ]:
list1 = ['orange','banana','orange']
'orange'in list1 

True

In [ ]:
list1 = ['orange','banana','orange']
list1

['orange', 'banana', 'orange']

In [ ]:
a = list1
a

['orange', 'banana', 'orange']

In [ ]:
a[2]='potato'
a

['orange', 'banana', 'potato']

In [ ]:
list1

['orange', 'banana', 'potato']

In [ ]:
list1

['milk', 'banana', 'potato']

In [ ]:
b=list1.copy()
b[0]= 'orange'
b

['orange', 'banana', 'potato']

In [ ]:
list1

['milk', 'banana', 'potato']

In [ ]:
list1 = ['orange','banana','orange']

In [ ]:
del list1

In [ ]:
list1

NameError: name 'list1' is not defined

In [ ]:
list1 = ['orange','banana','orange']
list1.pop(1)

'banana'

In [ ]:
list1 = [10,20,30,40]
list2= []
for i in list1 :
    list2.append(i*5) 
    print(list2)

[50]
[50, 100]
[50, 100, 150]
[50, 100, 150, 200]


In [ ]:
a = 'aditya'
a.swapcase()

'ADITYA'

In [ ]:
list1 = ['orange','banana','orange']
del list1

In [ ]:
list1


NameError: name 'list1' is not defined

In [ ]:
list1 = [10,20,30,40]
list2= []
for i in  list1 :
    list2.append(i*3)
    print(list2)



[30]
[30, 60]
[30, 60, 90]
[30, 60, 90, 120]


In [ ]:
file_name = ['doc1.ppt','doc2.jpg','doc3.pdf']
[ file.split('.')[-1] for file in file_name]

['ppt', 'jpg', 'pdf']

In [ ]:
file_name = ['doc1.ppt','doc2.jpg','doc3.pdf']
print([file for file in  file_name if file.endswith ('.ppt') ])

['doc1.ppt']


In [ ]:
z = [10,20,30]
z.pop()

30

In [ ]:
# enque and deque 
from queue import Queue
print_queue = Queue()
print_queue.put("print the 1 pdf")
print_queue.put("print the 2 pdf  ")
print_queue.put("print the 3 pdf ")
print_queue.put("print the 4 pdf ")

while not print_queue.empty ():
    print_job = print_queue.get()
    print ("print job", print_job )


print job print the 1 pdf
print job print the 2 pdf  
print job print the 3 pdf 
print job print the 4 pdf 


In [ ]:
t1=(10,20,20,300,3000)
t2=(30000,2000,1000,5000)


((10, 20, 20, 300, 3000), (30000, 2000, 1000, 5000))


In [ ]:
t3=(t1,t2)
t3

((10, 20, 20, 300, 3000), (30000, 2000, 1000, 5000))

In [ ]:
t1={10,20,20,300,3000}
t2={3000,2000,1000,500}
print(t1|t2)
print(t1&t2)
print(t1-t2)
print(t1^t2)


{1000, 10, 300, 2000, 20, 500, 3000}
{3000}
{10, 20, 300}
{1000, 10, 300, 2000, 500, 20}


In [ ]:
t1 = frozenset([10,20,20,300,3000])
type(t1)
t1

frozenset({10, 20, 300, 3000})

In [ ]:
t1.add(200)

NameError: name 't1' is not defined

In [ ]:
a ={'num1':[20,30,40],'name':'aditya','email':'akj@gmail.com','phone':(123,235)}
print(a)




{'num1': [20, 30, 40], 'name': 'aditya', 'email': 'akj@gmail.com', 'phone': (123, 235)}


In [ ]:
#zip 
students = ['aj','kj','rj']
marks = [10,20,15]
for i in zip (students , marks) :
    print(i)


('aj', 10)
('kj', 20)
('rj', 15)


In [ ]:
students = ['aj','kj','rj']
marks = [10,20,15]
students_marks={}
for student , mark in zip(students,marks):
    students_marks[student]= mark
    print(students_marks)

{'aj': 10}
{'aj': 10, 'kj': 20}
{'aj': 10, 'kj': 20, 'rj': 15}


In [ ]:
# comprehension

students = ['aj','kj','rj']
marks = [10,20,15]
{students:marks for students, marks in zip(students,marks) }

{'aj': 10, 'kj': 20, 'rj': 15}

In [ ]:
x = {1,2,2,3,3}
len(x)

3

In [ ]:
x = (1,2,3)
x2 = (4,5,6)
x+x2

(1, 2, 3, 4, 5, 6)

In [ ]:
t1 = (10,20,30,40)
print(type(t1))
print( t1 )


<class 'tuple'>
(10, 20, 30, 40)


In [ ]:
l1 = (list(t1) )
print(type(l1))
print(l1)

<class 'list'>
[10, 20, 30, 40]


In [ ]:

sorted(l1)

[10, 20, 30, 40]

In [ ]:
l1.append(200)
print(l1)

[10, 20, 30, 40, 200]


In [ ]:
print(l1)


[10, 20, 30, 40, 200]


In [ ]:
l1.insert(5,300)
print(l1)
l1.remove(300)
print(l1)



[10, 20, 30, 300, 300, 300, 300, 40, 200]
[10, 20, 30, 300, 300, 300, 40, 200]


In [ ]:
print( t1 )

[10, 20, 30, 40, 200, 50]


In [ ]:
t1 = (10,20,30,40)
print(type(t1))
print( t1 )

<class 'tuple'>
(10, 20, 30, 40)


In [ ]:
l1.extend(t1)
l1

[10, 20, 30, 300, 300, 300, 40, 200, 10, 20, 30, 40, 10, 20, 30, 40]

In [ ]:
l1.reverse()
l1

[40, 30, 20, 10, 40, 30, 20, 10, 200, 40, 300, 300, 300, 20, 10]

In [ ]:
l1.remove(30)
l1.pop()
l1

[40, 20, 10, 40, 20, 10, 200, 40, 300, 300, 300, 20]

In [ ]:
l1.pop(0)
l1

[20, 40, 20, 10, 200, 40, 300, 300]

In [ ]:
l1


[20, 40, 20, 10, 200, 40, 300, 300]

In [ ]:
l1.remove(40)
l1


[20, 20, 10, 200, 300, 300]

In [ ]:
remove = l1.pop(-1)
l1

[20, 20, 10, 200, 300]

In [ ]:
import math as m 

In [ ]:
m.ceil(5.7)

6

In [ ]:
m.floor(5.9)

5

In [ ]:
def greeting(name ):
    print("hello ",name)

In [ ]:
greeting('chetan')

hello  chetan


In [ ]:
def func():
    return "this is my first program"
func() +  " in python "

'this is my first program in python '

In [ ]:
def func():
    calc = 20+20+30*50
    return calc
print(func())

1540


In [ ]:
def cube_no(a):
    return a*a*a
cube_no(5)

125

In [ ]:
def add(a ,b):
    return a+b
add(800 ,200)
add("hii", "cutie")
add(a ="cutie",b ="hii")

'cutiehii'

In [ ]:
# default args # we can take default arg in last of the function  
def sum(b, c, a=5):
    return a+b+c
sum(b=30,c=20)

55

In [ ]:
def add_two_number():
    a = int(input("enter first number"))
    b = int(input("enter first number"))
    return a+b
print(add_two_number())

527


In [ ]:
def num(c):
    n = []
    for i in c: 
        if type(i) == int or type(i) == float:
            n.append(i)
    return n 
num([2,2.2,"aj"])


[2, 2.2]

In [ ]:
def num(c):
    n = []
    for i in c: 
        if type(i) == list:  
            for j in i :
                if type(j) == int or type(j) == float:
                    n.append(j)
        else:
           if type(i) == int or  type(i)== float:
            n.append(i)
    return n 
print(num([3,3.3,3j+5,"ajay"]))

[3, 3.3]


In [ ]:
# varible name of ARGS >> when we dont know the no of args >> which can take n no values 
def sum1(*args):
    s =0 
    for i in args:
        s = s+1
    return s
print(sum1(1,2,3))

 


3


In [ ]:
def return_list(*args):
    l =[]
    for i in args:
        if type(i) == list:
            l.append(i) 
            return l
print(return_list(1,2,3.3,[1,2,3,4,5],2+3j,True))
 


[[1, 2, 3, 4, 5]]


In [ ]:
subpart = "i am very excited"
def greet():
    message = "hey chetan ,"+ subpart
    print(message)
greet()

hey chetan ,i am very excited


In [ ]:
# fuction inside the functions 
def marks_in_subject(**kwargs):
    def total_marks(marks_list):
        return sum(marks_list)
    marks_list = []
    for sub, marks in kwargs.items():
        marks_list.append(marks)

    return total_marks(marks_list)
marks_in_subject(a= 30 , b=40)
    

70

In [ ]:
a = iter({1,2,3})
next(a)
a

In [ ]:
a = iter({'a':'b'})
a
next

In [ ]:
a = float(input('Enter the number: '))

In [ ]:
def square(n):
    result = []
    for i in n:
        result.append(i**2)
    return result 
square([10,20,30])

[100, 400, 900]

In [ ]:
# for this type of output take range function in for loop
def cube_number(a):
    result = []
    for i in range(a) :
        result.append(i**3)
    return result
cube_number(5)
    

[0, 1, 8, 27, 64]

In [ ]:
def square(n):
  for i in range(n):
    yield i**2
square(10)

<generator object square at 0x000001E634D3D150>

In [ ]:
# lambda functions >> anonymous function in with no need of return statement 
odd = lambda x : x%3 == 1
odd(5) 



False

In [ ]:
ln = lambda x : len(x)
ln("aditya")

6

In [ ]:
def fac(n):
    if n == 0 :
        return 1 
    else : 
        return n*fac(n-1)
fac(5)

120

In [ ]:
fac= lambda n:1 if n== 0 else n*fac(n-1)
fac(5)

120

In [ ]:
#map function  
l = [1,2,34,5]
def square(x):
    sq = []
    for i in x :
        sq.append(i**2)
    return sq
square(l)

[1, 4, 1156, 25]

In [ ]:
l

[1, 2, 34, 5]

In [ ]:
def square (x):
    return x**2



In [ ]:
l

[1, 2, 34, 5]

In [ ]:
list(map(square,l))

[1, 4, 1156, 25]

In [ ]:
def mul(x):
    return x*2
list(map(mul,l))

[2, 4, 68, 10]

In [ ]:
list(map(lambda x:x+10,l))

[11, 12, 44, 15]

In [ ]:
list(map(lambda x:x%10,l))

[1, 2, 4, 5]

In [ ]:
list(map(lambda x : x/8,l))

[0.125, 0.25, 4.25, 0.625]

In [ ]:
l = ["1", "2" , "4", "5"]
list(map(lambda x:int(x),l))

[1, 2, 4, 5]

In [ ]:
l = ["1", "2" , "4", "5"]
list(map(lambda x:float(x),l))

[1.0, 2.0, 4.0, 5.0]

In [ ]:
l1 = [2, 4, 68, 10]
l2 = [2, 4, 68, 10]
list(map(lambda x,y: x+y,l1,l2 ))

[4, 8, 136, 20]

In [ ]:
grades=["A","B","C"]
list(map(lambda grades: 4 if grades=="A"else (3 if grades =="B" else 2 ),grades))

[4, 3, 2]

In [ ]:
# reduce function 
from functools import reduce

l = [1, 2, 3, 4, 5, 6]
reduce(lambda x, y: x + y, l)



21

In [ ]:
from functools import reduce
l = [1, 2, 3, 4, 5, 6]
reduce(lambda x, y: x * y, l)



720

In [ ]:
numbers = [1,2,3,4,1000,6]
reduce(lambda x,y:x if x>y else y,numbers)

1000

In [ ]:
# filter function 
l

[1, 2, 3, 4, 5, 6]

In [ ]:
list(filter(lambda x : x%2 ==0,l))

[2, 4, 6]

In [ ]:
def multiply(a, b):
    return a*b
multiply(4*3)

TypeError: multiply() missing 1 required positional argument: 'b'

In [ ]:
double 

In [ ]:
nums= [1,2,3,4]
result = list(map(lambda x:x**2,nums))
print(result)


[1, 4, 9, 16]


In [ ]:
from functools import reduce
num =  [1,2,3,4]
result = reduce(lambda x,y:x*y,nums)
print(result)


24


In [ ]:
def hello():
    return "hello world"
print(hello)
    

<function hello at 0x00000240169FB600>


In [ ]:
a =[10,20,30,40]
a


[10, 20, 30, 40]

In [ ]:
import numpy as np
np.mean(a)


np.float64(25.0)

In [ ]:
np.median(a)

np.float64(25.0)

In [ ]:
a=[2,4,1,3,5]
np.median(a)

np.float64(3.0)

In [ ]:
a = [1,1,2,3,4,4,4,5,6]
a

[1, 1, 2, 3, 4, 4, 4, 5, 6]

In [ ]:
from scipy import stats
stats.mode(a)


ModeResult(mode=np.int64(4), count=np.int64(3))

In [ ]:
a = [1,1,2,3,4,4,4,5,6]
from scipy import stats
stats.mode(a)

ModeResult(mode=np.int64(4), count=np.int64(3))

In [ ]:
import statistics 
statistics.mode(a)
statistics.mean(a)
statistics.median(a)



4

In [ ]:
statistics.mean(a)

3.3333333333333335

In [ ]:
statistics.median(a)

4

In [ ]:
a = [1,1,2,3,4,4,4,5,6]
a

[1, 1, 2, 3, 4, 4, 4, 5, 6]

In [ ]:
# meausre of dispersion 
# 1.range
max(a)-min(a)


5

In [ ]:
# percentile
import numpy as np
np.percentile(a,[25,30,75,100])


array([2. , 2.4, 4. , 6. ])

In [ ]:
#IQR
6-2.4

3.6

In [ ]:
# box plot 
import seaborn as sns
sns.boxplot(a)

NameError: name 'a' is not defined

In [ ]:
#OOops
class Car :
    def accelerate(self):
        print("car is accelerating")
    def stop(self):
        print("car is stopping")
a = Car()
a.accelerate()
a.stop()


car is accelerating
car is stopping


In [ ]:
class Bank :
    def deposit(self):
        print("money is depositting")
    def withdraw(self):
        print("money is withdrawing")
        
        
a = Bank()
a.deposit()
a.withdraw()


money is depositting
money is withdrawing


In [ ]:
#passing data in the class
class Bank :
    def deposit(self,amount):
        print("money is depositting")
    def withdraw(self,amount_withdraw):
        print("money is withdrawing")
        
        
a = Bank()
a.deposit(1000)
a.withdraw(100)


money is depositting
money is withdrawing


In [ ]:
class Listoops:
    l = [1, 2, 3, 4, 5, 6, 7, 8]

    def even_no(self, l):
        l1 = []
        for i in l:
            if i % 2 == 0:
                l1.append(i)
        return l1

    def odd_no(self, l):
        l1 = []
        for i in l:
            if i % 2 != 0:
                l1.append(i)
        return l1
a = Listoops()
print(a.l)
print(a.even_no(a.l))
print(a.odd_no(a.l))









 

[1, 2, 3, 4, 5, 6, 7, 8]
[2, 4, 6, 8]
[1, 3, 5, 7]


In [ ]:
class father : 
    def father (self):
        print("father is the property")
class child(father) :
    def child(self):
        print("son has the property for job")
child_obj= child()
child_obj.father()
child_obj.child()


father is the property
son has the property for job


In [ ]:
class fruit :
    def fruit_info(self):
        print("inside the parent class")
class apple(fruit):
    def fruit_info(self):
        print("inside the child class")
    def apple_info(self):
        print("inside the child class")


obj = apple()
obj.fruit_info()
obj.apple_info()
                         
        

inside the child class
inside the child class


In [ ]:
# multilevelling in heritance 
class animal :
    def animal_sound(self):
        print("every animal has a different sound")
class Tiger(animal):
    def Tiger_sound(self):
        print("tiger is roaring")
class cub(Tiger):
    def cub_sound(self):
        print("cub is chirping")
obj = cub()
obj.animal_sound()
obj.Tiger_sound()
obj.cub_sound()


every animal has a different sound
tiger is roaring
cub is chirping


In [ ]:
# multiple inheritance 
class  animal :
    def animal_sound(self):
        print("every animal has a different sound")
class Tiger:
    def Tiger_sound(self):
        print("tiger is roaring")
class cub(animal,Tiger):
    def cub_sound(self):
        print("cub is chirping")
obj = cub()
obj.animal_sound()
obj.Tiger_sound()

obj.cub_sound()

every animal has a different sound
tiger is roaring
cub is chirping


In [ ]:
# diamond method 
class a :
    def method(self):
        print("method of a class a")
class b(a):
    def method(self):
        print("method of a class b")
class c(a):
    def method(self):
        print("method of a class c")
class d(c,b):
    pass

D = d()
D.method


<bound method c.method of <__main__.d object at 0x0000025A94079940>>

In [ ]:

D = d()
D.method

<bound method c.method of <__main__.d object at 0x0000025A94036990>>

In [ ]:
# hierarchical inherirtance 
class vehicle:
    def info(self):
        print("This is vehicle ")
class car(vehicle):
    def car_info(self,name):
        print("This is car_info ",name)
class bike(vehicle):
    def bike_info(self,name):
        print("This is bike_info ",name)

c= car()
c.info()
c.car_info("Ferrai")

b = bike()
b.info()
b.bike_info("ninja")



 

This is vehicle 
This is car_info  Ferrai
This is vehicle 
This is bike_info  ninja


In [ ]:
# hybrid inheritance >>> multiple types or combinations of diff inheritance 
class vehicle:
    def info(self):
        print("This is vehicle ")
class car(vehicle):
    def car_info(self):
        print("This is car_info ")
class bike(vehicle):
    def bike_info(self,name):
        print("This is bike_info ",name)
class truck(vehicle):
    def truck_info(self,name):
        print("This is truck_info ",name)
        
c = car()       
c.car_info()            
        
b = bike()
b.info()         
b.bike_info("Pulsar")

t = truck()
t.info()
t.truck_info("Tata")


        



This is car_info 
This is vehicle 
This is bike_info  Pulsar
This is vehicle 
This is truck_info  Tata


In [ ]:
# abstraction >>>> hiding of complex implementatiton 
# hiding uneeded details and expoising required 
# it can not make object
# it is always be subclassed in 
#it is may conatains methods that are declare and not implemented


In [ ]:
# example 
import abc 


In [ ]:
class pw_skils:
    @abc.abstractmethod
    def student_details(self):
        pass
    @abc.abstractmethod
    def student_assignment(self):
        pass
    @abc.abstractmethod
    def student_marks(self):
        pass

In [ ]:
class DS :
    def student_details(self):
        return " ds class details"
    def student_assignment(self):
        return "this is my assignment of ds"
    def student_marks(self):
        return "this is my assignment marks"

d = DS()
d.student_assignment()


'this is my assignment of ds'

In [ ]:
d.student_details()

' ds class details'

In [ ]:
d. student_marks()

'this is my assignment marks'

In [ ]:
# polymorphism & encapsulation
class teacher_lecture:
    def lec_info(self):
        print("this is lec info with teacher perspective")

class student_lecture:
    def lec_info(self):
        print("this is lec info with student perspective")

In [ ]:
obj1 = teacher_lecture()
obj2 = student_lecture()

class_obj = [obj1,obj2]

In [ ]:
def parser(class_obj):
    for i in class_obj:
        i.lec_info()
        
parser(class_obj)        


this is lec info with teacher perspective
this is lec info with student perspective


In [ ]:
# method overloading
class student:
    def student(self):
        print("hello teacher")
    def student(self, name=""):
        print("hello teacher",name)    
    def student(self,name="",course=""):
        print("hello teacher",name,course)
        
stud = student()
stud.student()
stud.student("chavan sir")
stud.student("chavan sir","Mca")


hello teacher  
hello teacher chavan sir 
hello teacher chavan sir Mca


In [ ]:
class animal :
    def animal_sound(self):
        print("animal sound")
class cat(animal):
    def cat_sound(self):
        print(" cat said meaow") 

c = cat()
c.animal_sound()
c.cat_sound()  
             

animal sound
 cat said meaow


In [ ]:
# Encapsulation >>> hiding something
#access modifier >>> public,protected,private

In [ ]:
z

In [ ]:
class student :
    def _init__(self,name,degree):
        self.name = name
        self.degree = degree 
        
        
stud = student("ram","mca")
stud.name
stud.degree



'ram'

In [ ]:
stud.degree

'mca'

In [ ]:
stud1 = student("sam","bach")
stud1.degree

'bach'

In [ ]:
stud1.degree ="phd"
stud1.degree


'phd'

In [ ]:
# datra tool method PRIVATE >>>> the data only and method only accessible within its class using __ to make private
class student :
    def __init__(self,name,degree):
        self.name = name 
        self.__degree = degree #private
    def show(self):
        print("name",self.name,"degree",self.__degree)    
stud = student("aj","mca")
stud.name
stud.show()


name aj degree mca


In [ ]:
stud.name

'aj'

In [ ]:
stud._student__degree

'mca'

In [ ]:
stud._student__degree # only way to access the private variabale

'mca'

In [ ]:
# method private
class student :
    def __init__(self,name,degree):
        self.name = name 
        self.__degree = degree #private
    def __show(self):
        print("name",self.name,"degree",self.__degree)   
    def __private_method(self) :
        print("this is a private method")    

stud = student("aj","mca")
stud.name
stud.show()
stud._student__degree
stud._student__private_method()

                 


In [ ]:
stud._student__show()

name aj degree mca


In [ ]:
# accesss private method
class student :
    def __init__(self,name,degree):
        self.name = name 
        self.__degree = degree #private
    def __show(self):
        print("name",self.name,"degree",self.__degree)   
    def __private_method(self) :
        print("this is a private method")
    def access_private_method(self):
        self.__private_method() 


In [ ]:
stud = student("aj","mca")
stud.access_private_method()


this is a private method


In [ ]:
#protected >>> it can be accessed within class and subclass using (_)

class college:
    def __init__(self):
        self._college_name = "VVPIET"   # protected member

class student(college):
    def __init__(self, name):
        self.name = name
        college.__init__(self)  # accessing parent class constructor

    def show(self):
        print("name", self.name, "college", self._college_name)

stud = student("ram")
stud.name
stud.show()

     

name ram college VVPIET


In [ ]:
#super class 
class college:
    def __init__(self):
        self._college_name = "VVPIET"   # protected member

class student(college):
    def __init__(self, name):
        self.name = name
        super().__init__()  # accessing parent class constructor

    def show(self):
        print("name", self.name, "college", self._college_name)

stud = student("ram")
stud.name
stud.show()

name ram college VVPIET


In [ ]:
# class method : A class method is a method that is bound to the class, not to the object (instance).
class student :
    def __init__(self,name):
        self.name = name 
        
    @classmethod #>>>.is is access vthe 
    def student_details(cls,name):
        return cls(name)#>>Here, cls.college accesses the class variable, not instance data
    
ob = student.student_details("aj")
ob.name
        
        



'aj'

In [ ]:
class animal : 
    def __init__(self, name):#instance method 
        self.name = name 
        
    @classmethod 
    def Animal_name(cls,name1):
        return cls(name1)
    
obj = animal.Animal_name("vivek bhave")
obj.name
        
#>> it is still gives the o/p despite we take the name1 in calling due to the overloading in __init__ method 

'vivek bhave'

In [ ]:
# class method can modify state applicable to all instances of th class
# instance method 

class student :
    total_student = 0
    def __init__(self,name):#instance method
        self.name =name 
        student.total_student = student.total_student+1 # totalstudent is the class variable to all the instances 
        
    @classmethod
    def get_total_students(cls):
        return cls.total_student
    
student.total_student

        
 

0

In [ ]:
stud1 = student("aj")
stud2= student("rj")
stud1.name


'aj'

In [ ]:
stud2.name

'rj'

In [ ]:
# external func as part of class method 

def course_details(cls, course_name):
    print("course is:", course_name)

student.course_details = classmethod(course_details)

student.course_details("ds")

course is: ds


In [ ]:
del student.course_details

In [ ]:
student.course_details("ds")

AttributeError: type object 'student' has no attribute 'course_details'

In [ ]:
# static method 
# it does not modify the class
# not depend any class
# doesnt access the instance 
# @static method is used 
# works with parameters that we passed

In [ ]:
class calculator :
    @staticmethod 
    def add(x,y):
     return x+y

calculator.add(5,5)



10

In [ ]:
class calculator :
    @staticmethod 
    def sub(x,y):
     return x-y

calculator.sub(5,5)

0

In [ ]:
# dunder methods :
a = 2
b = 3
a.__add__(b)

5

In [ ]:
#__init__ >> used to initialiaze new instance 
class student:
    def __init__(self,name):
        print(name,"hey whats up bro")
        
obj = student("aj")

aj hey whats up bro


In [ ]:
# __new__ >>> it is reponsible to create new instance of the class 

class student :
    def __new__(self):
        print("this will be executed before the init")
    def __init__(self,name):
        print("this will be excuted after the new ")    
        
obj = student()

this will be executed before the init


In [ ]:
# __str__ >>>it  will  return string representation of method 

class student :
    def __init__(self):
        self.phoen = 333333333
    def __str__(self):
        return "this will be overloading the print statement of object method"
        
print(student())
    

this will be overloading the print statement of object method


In [ ]:
# __repr__ >>> it is returns unclear string representation of the object as it is that can be used representation
class student :
    def __init__(self, name,age):
        self.name = name
        self.age = age
    def __repr__(self):
        return f"student(name={self.name},age ={self.age} )"
    
 
obj =student("ram",20)

print(obj)


student(name=ram,age =20 )


In [ ]:
#__eq__(equal)>>>comparing equal or not 
class point :
    
 def __init__(self,x,y):
    self.x = x
    self.y = y
 def __eq__(self,other):
    return self.x==other.x and self.y == other.y

p1 = point(1,3)
p2 = point(1,3)
print(p1==p2)


True


In [ ]:
# __add__ : 
class point:
    
    def __init__(self, x, y):
        self.x = x
        self.y = y

    def __add__(self, other):
        return point(self.x + other.x, self.y + other.y)

p1 = point(1, 3)
p2 = point(1, 3)
p3 = p1 + p2

print(p3.x, p3.y)


2 6


In [ ]:
# decorators >>> it is allows to modify or extend the behaviour or functions without directly modifying their code 

In [ ]:
# function decorator
def my_decorator():
    print('start')
    print(2*1000)
    print('end')
my_decorator()

start
2000
end


In [ ]:
def my_decorator(func):
    def wrapper():
        print("the line before the computation")
        func()
        print("the line after the computation")
    return wrapper

@my_decorator    
def say_hello():
    print("hello")
    
say_hello()
    
    


    


the line before the computation
hello
the line after the computation


In [ ]:
import time
def timer_decorator(func):
    def timer():
        start = time.time()
        func()
        end =time.time()
        print("the time for executing the code",end-start)
    return timer

@timer_decorator
def func_test():
    print(1100000*1000)
func_test()

    


1100000000
the time for executing the code 0.0017023086547851562


In [ ]:
# class decorator
class mydecorator :
    def __init__(self,func):
        self.func = func
    def __call__(self): #>>__call__ =:If the decorator class has a __call__ method, then the resulting object becomes callable like a functio
         print("something is happening before the fuction.")
         self.func()
         print("something is happening after the fuction.")
     
       
@mydecorator
def say_hello():
    print("hello aj")
say_hello()
    

something is happening before the fuction.
hello aj
something is happening after the fuction.


In [ ]:
class mydecorator :
    def __init__(self,func):
        self.func = func
        print("inside the init method")
    def __call__(self):
        print("something is happening before the fuction.")
        self.func()
        print("something is happening after the fuction.")
        
@mydecorator
def say_hello():
    print("hello aj")
say_hello()       
        


inside the init method
something is happening before the fuction.
hello aj
something is happening after the fuction.


In [ ]:
#inbuilt method 
#@classmethod >>> the method takes the class itself as the first argument 

In [ ]:
class math :
    @classmethod
    def add(cls,x,y):
        return cls.__name__,x+y
math.add(3,5)

('math', 8)

In [ ]:
#@static method

In [ ]:
class math:
    @staticmethod 
    def add(x,y):
        return x+y
  
math.add(2,4)
   


6

In [ ]:
# property decorator 

In [ ]:
class student :
    def __init__(self,name,marks):
        self.name=name
        self.marks = marks 
    @property
    def result(self):
        return "pass" if self.marks >= 35 else "fail"
    
s = student("aj",45)
s.result


'pass'

In [ ]:
# property dcoretor 

In [ ]:
class student:
    def __init__(self,name,price):
        self.__name = name
        self.__price = price 
        
stud = student("aj",40)
stud._student__name
      

'aj'

In [ ]:
class student:
    def __init__(self,name,price):
        self.__name = name
        self.__price = price
    @property    
    def access_price(self):
        return  self.__price
    
stud = student("aj",400)
stud.access_price  


400

In [ ]:
#modification
class student:
    def __init__(self, name, price):
        self.__name = name
        self.__price = price

    @property
    def access_price(self):
        return self.__price

    @access_price.setter
    def access_price(self, price_new):
        self.__price = price_new

    @access_price.deleter
    def access_price(self):
        del self.__price


stud = student("aj", 400)
print(stud.access_price)   

     
 

400


In [ ]:
stud.access_price = 2000     # SET
print(stud.access_price)

2000


In [ ]:
# File handling 


In [ ]:
# write = "w"
file = open("data.txt", "w")
file.write("Hello aditya\n")
file.write("Hello samarth\n")
file.write("Hello farhan\n")
file.write("Hello atharva\n")
print(file.tell())
file.close()


58


In [ ]:
#close()
file.closed

True

In [ ]:
name()
file.name

'data.txt'

In [ ]:
# append = "a"
file = open("data.txt","a")
file.write("hello jay\n")
file.close()

In [ ]:
file = open("data.txt","r")
print(file.readlines())
file.close()

['Hello aditya\n', 'Hello samarth\n', 'Hello farhan\n', 'Hello atharva\n']


In [ ]:
#present working directory 
import os
os.getcwd()

'c:\\Users\\ashis\\OneDrive\\Desktop\\code'

In [ ]:
ls

 Volume in drive C is Windows
 Volume Serial Number is 64EB-A5A8

 Directory of c:\Users\ashis\OneDrive\Desktop\code

02/25/2026  09:10 PM    <DIR>          .
02/23/2026  12:51 AM    <DIR>          ..
11/25/2025  10:30 PM               105 animal.java
11/25/2025  10:37 PM               115 animal2.jav
10/31/2025  01:28 PM               401 code.class
10/31/2025  01:28 PM             1,142 code.java
10/31/2025  12:46 PM            97,822 code.png
11/25/2025  10:31 PM               248 cub.java
02/25/2026  09:29 PM                58 data.txt
12/24/2025  08:41 PM                23 demo.py
11/25/2025  10:39 PM                80 dog.java
11/25/2025  10:37 PM                 2 main.java
10/17/2025  09:38 PM               550 test.class
02/25/2026  09:42 PM           116,702 test.ipynb
11/08/2025  09:33 PM               118 tiger.java
              13 File(s)        217,366 bytes
               2 Dir(s)  96,706,473,984 bytes free


In [ ]:
os.path.getsize("data.txt")

58

In [ ]:
os.mkdir("test python/test")

In [ ]:
os.makedirs("1/2/3/4")

In [ ]:
os.listdir()

['1',
 'animal.java',
 'animal2.jav',
 'code.class',
 'code.java',
 'code.png',
 'cub.java',
 'data.txt',
 'demo.py',
 'dog.java',
 'main.java',
 'test python',
 'test.class',
 'test.ipynb',
 'tiger.java']

In [ ]:
os.mkdir("aj")

In [ ]:
os.mkdir("aj/aj2")

In [ ]:
os.getcwd()

'c:\\Users\\ashis\\OneDrive\\Desktop\\code'

In [ ]:
file=open("c:\\Users\\ashis\\OneDrive\\Desktop\\code\\aj/aj2/file.txt","w")

In [ ]:
import shutil
shutil.copy("c:\\Users\\ashis\\OneDrive\\Desktop\\code\\aj/aj2/file.txt",'c:\\Users\\ashis\\OneDrive\\Desktop\\code')

'c:\\Users\\ashis\\OneDrive\\Desktop\\code\\file.txt'

In [ ]:
with open ("test/test1.txt","w") as file:
    file.write("hello world")

In [ ]:
with open ("test/test1.txt","r") as file:
   line = file.readline()
   print(line)

hello world


In [ ]:
file_text =  """
example1
example2
example3
"""

In [ ]:
with open("data.txt","w") as file :
    file.write(file_text)
    
    
    

In [ ]:
with open("data.txt","r") as file :
    data = file.read()
print(data)


example1
example2
example3



In [ ]:
#csv>>> comma seperated vlaues  
data = [["name","course","fee"],
        ["aj","mca","75000"],
        ["ag","mca","8000"]]

In [ ]:
for i in data:
    print(i)

['name', 'course', 'fee']
['aj', 'mca', '75000']
['ag', 'mca', '8000']


In [ ]:
import csv 
with open("data.csv","w") as file:
    w = csv.writer(f)
    for i in data :
        w.writerow(i)

In [ ]:
import csv 
with open("data.csv","r") as file:
    r = csv.reader(file)
    for i in r :
         print(i)

['name', 'course', 'fee']
[]
['aj', 'mca', '75000']
[]
['ag', 'mca', '8000']
[]


In [ ]:
# json >> js pbject notation 
data = { "name":"aj",
        "course":"mca",
        "fees":3000}
data

{'name': 'aj', 'course': 'mca', 'fees': 3000}

In [ ]:
import json 
with open("data.json","w") as file:
     json.dump(data,file)
    


In [ ]:
with open("data.json","r") as file:
    data = json.load(file)
print(data)

{'name': 'aj', 'course': 'mca', 'fees': 3000}


In [ ]:
# write a binary data in a file 
with open("data.bin","wb") as file:
     file.write(b"\x48\x65\x6c\x6c")

In [ ]:
with open("data.bin","rb") as file:
    print(file.read())

b'Hell'


In [ ]:
# buffer reading and writing 
import io 
with open("data.bin","wb") as file:
    buffer = io.BufferedWriter(file)
    file.write(b"DS has many meanings depending on context, most commonly referring to Data Source\n")
    file.write(b"hello everyone, myself aditya\n")
    file.write(b"i am currently exhausted\n")
    file.flush()
    

In [ ]:
with open("data.bin","rb") as file:
     buffer = io.BufferedReader(file)
     data = file.read(1000)
    
print(data)


b'DS has many meanings depending on context, most commonly referring to Data Source\nhello everyone, myself aditya\ni am currently exhausted\n'


In [ ]:
# exception handling 
# try block :
try:
    f = open("example.txt","r")
except Exception as e:
    print("there is an issue with the code and the issue is:",e)
    print(6+3)
    print("this file is opened and now i am performed whatever idk")   

there is an issue with the code and the issue is: [Errno 2] No such file or directory: 'example.txt'
9
this file is opened and now i am performed whatever idk


In [ ]:
try:
    5/0
except Exception as e :
    print("this block is not executed due to,",e)
else:
    print("this will be executed")    

    

this block is not executed due to, division by zero


In [ ]:
try:
    f= open("example.txt","r")
except Exception as e:
    print("there is an issue with the code and issue is:",e)
else:
    print("this block is executed if try block is executed without anr exception")    
    

there is an issue with the code and issue is: [Errno 2] No such file or directory: 'example.txt'


In [ ]:
try:
    f= open("example.txt","w")
except Exception as e:
    print("there is an issue with the code and issue is:",e)
else:
    print("this block is executed if try block is executed without any exception")    
    

this block is executed if try block is executed without any exception


In [ ]:
# finally block :
try:
    f= open("example.txt","w")
    f.write("hello world")
except Exception as e:
    print("there is an issue with the code and issue is:",e)
else:
    f.close()
    print(5*9)
    print("this block is executed if try block is executed without any exception")
finally :
    print("this block is  always executed ")    
    

45
this block is executed if try block is executed without any exception
this block is  always executed 


In [ ]:

def salary_validation(salary):
    if salary <= 0:
        print("negative salary is impossible")
    elif salary >= 3000000:
        print("salary is unexpected")
    else :
        print("salary is valid")
        
salary_validation(500)
    

salary is valid


In [ ]:
class validatesalary(Exception):
    def __init__(self,msg):
        self.msg=msg

In [ ]:

def salary_validation(salary):
    if salary <= 0:
        raise("negative salary is impossible")
    elif salary >= 3000000:
        raise("salary is unexpected")
    else :
        print("salary is valid")


In [ ]:
try :
    salary = int(input("Enter your salary: "))
    salary_validation(salary)
except validatesalary as e:
    print(e)
    

    

salary is valid


In [ ]:
try :
    int("pwskills")
except ValueError as e:
    print("this string can not be converted into integer",e)

this string can not be converted into integer invalid literal for int() with base 10: 'pwskills'


In [ ]:
#handling two specific errors :
try:
    10/'3'
except TypeError as e :
    print("some 'str' used in division ",e)
    print("The calc is:",10/int("3"))

some 'str' used in division  unsupported operand type(s) for /: 'int' and 'str'
The calc is: 3.3333333333333335


In [ ]:
#handling two specific exception :
try:
    10/'3'
except (ZeroDivisionError,TypeError) as e :
    print("This div is not possible due to the error>>>>>",e)
   

This div is not possible due to the error>>>>> unsupported operand type(s) for /: 'int' and 'str'


In [ ]:
try:
    10/0
except (ZeroDivisionError,TypeError) as e :
    print("This div is not possible due to the error>>>>>",e)

This div is not possible due to the error>>>>> division by zero


In [ ]:
#handling two multiple exception in seperate blocks :
try:
    10/0
except (ZeroDivisionError,TypeError) as e :
    print("This div is not possible due to the error>>>>>",e)
except ValueError as e :
    print("This is Value Error>> ",e)


This div is not possible due to the error>>>>> division by zero


In [ ]:
try :
    d ={"name":"aditya","course":"mca"}
    d = {"age"}
except KeyError as e :
    print("the key is not found",e)

In [ ]:
try:
    f=open("example.txt","r")
    data=f.read()
    print(data)
    f.close()
except FileNotFoundError as e :
    print("following file is not created, re run the code",e)


hello world


In [ ]:
# when you not know the possible exceptions:
try:
    f=open("example.txt","r")
    f.read()
except FileNotFoundError as e :
    print("following file is not created, re run the code",e)
except Exception as e :
    print("first msg------File is not opened due to",e)
finally :
    f.close()


In [ ]:
# with log:
import logging 
logging.basicConfig(filename="program.log",level= logging.DEBUG)
try:
    f=open("example.txt","r")
    data=f.read()
    print(data)
    
except FileNotFoundError as e :
    logging.error(f"following file is not created, re run the code{e}")
finally:
    f.close()
 


hello world


In [ ]:
# LOGGGING AND DEBUGGING :


In [ ]:
# print statement 

def divide(a,b):
    print(a,b)
    if b==0:
        #print("zero division error")
        return
    return a/b

for i in range(-10,10):
    #print(i,i+1)
    divide(i,i+1)

-10 -9
-9 -8
-8 -7
-7 -6
-6 -5
-5 -4
-4 -3
-3 -2
-2 -1
-1 0
0 1
1 2
2 3
3 4
4 5
5 6
6 7
7 8
8 9
9 10


In [ ]:
# logging 

import logging 
logging.basicConfig(filename="test.log",level=logging.INFO)
logging.info("this is normal info about the software")
logging.warning("there is empty list here")
logging.debug("the length of the list here ")
logging.error("some error has happened")
logging.critical("the software is stopped running")
logging.shutdown()



In [ ]:
import logging 
logging.basicConfig(filename="test_new.log",level=logging.DEBUG, format ='%(asctime)s %(message)s')
logging.debug("this is debugging")
logging.info("this is normal info about the software")
logging.warning("there is empty list here")
logging.shutdown()



In [ ]:
import logging 
logging.basicConfig(filename="test1_new.log",level=logging.DEBUG, format =' %(asctime)s %(levelname))s')
logging.debug("this is debugging")
logging.info("this is info")
logging.warning("there is warning msg")
logging.shutdown()

In [ ]:
#multithreading
import time 
start = time.perf_counter()

def test_func():
    print("do something")
    print("slepp")
    time.sleep(1)
    print("done with sleeping")
test_func()
test_func()

end = time.perf_counter()

print(f"the program finished in{round(end-start,2)}seconds")



do something
slepp
done with sleeping
do something
slepp
done with sleeping
the program finished in2.01seconds


In [ ]:
import time 
import threading
start = time.perf_counter()

def test_func():
    print("do something")
    print("sleep")
    time.sleep(1)
    print("done with sleeping")
    
t1 = threading.Thread(target=test_func)
t2 = threading.Thread(target=test_func)

t1.start()
t2.start()

t1.join()
t2.join()

end = time.perf_counter()

print(f"the program finished in{round(end-start,2)}seconds")

do something
sleep
do something
sleep
done with sleeping
done with sleeping
the program finished in1.03seconds


In [ ]:
import time 
import threading
start = time.perf_counter()

def test_func():
    print("do something")
    print("sleep")
    time.sleep(1)
    print("done with sleeping")
    
threads =[]
for i in range(9): 
    t = threading.Thread(target=test_func)
    t.start()
    threads.append(t)

for thread in threads:
    thread.join()


end = time.perf_counter()

print(f"the program finished in{round(end-start,2)}seconds")

do something
sleep
do something
sleep
do something
sleep
do something
sleep
do something
sleep
do something
sleep
do something
sleep
do something
sleep
do something
sleep
done with sleeping
done with sleeping
done with sleeping
done with sleeping
done with sleeping
done with sleeping
done with sleeping
done with sleeping
done with sleeping
the program finished in1.03seconds


In [ ]:
#use cases:
import time 
import threading


start = time.perf_counter()
url_list =[
    'https://pwskills.com/learn/course/data-science-with-generative-ai%20-%202/6891900c886386abb4705279/lesson/68d3c9a0335a87a5c26b2c23/?milestoneId=68ac58db85c44b16e9d24d64&from=%2Flearn%2Fcareer-path%2Fdata-science-with-generative-ai+-+2%2F6891900c886386abb4705279%2Fdashboard%2F%3Ffrom%3D%2Fdashboard%2Foverview&clickText=start_journey&page_from=career_path_page&section=your_track&year=689d8a8892b10554b48b4be7&megaSection=learn&yearName=Self+Paced&sectionId=68d3c9a0335a87a5c26b2ca1&lectureType=video',   
    'https://pwskills.com/learn/course/data-science-with-generative-ai%20-%202/6891900c886386abb4705279/lesson/68d3c9a0335a87a5c26b2c23/?milestoneId=68ac58db85c44b16e9d24d64&from=%2Flearn%2Fcareer-path%2Fdata-science-with-generative-ai+-+2%2F6891900c886386abb4705279%2Fdashboard%2F%3Ffrom%3D%2Fdashboard%2Foverview&clickText=start_journey&page_from=career_path_page&section=your_track&year=689d8a8892b10554b48b4be7&megaSection=learn&yearName=Self+Paced&sectionId=68d3c9a0335a87a5c26b2ca1&lectureType=video',   
    'https://pwskills.com/learn/course/data-science-with-generative-ai%20-%202/6891900c886386abb4705279/lesson/68d3c9a0335a87a5c26b2c23/?milestoneId=68ac58db85c44b16e9d24d64&from=%2Flearn%2Fcareer-path%2Fdata-science-with-generative-ai+-+2%2F6891900c886386abb4705279%2Fdashboard%2F%3Ffrom%3D%2Fdashboard%2Foverview&clickText=start_journey&page_from=career_path_page&section=your_track&year=689d8a8892b10554b48b4be7&megaSection=learn&yearName=Self+Paced&sectionId=68d3c9a0335a87a5c26b2ca1&lectureType=video'  
]
data_list = ["data1.txt","data2.txt","data3.txt"]


import urllib.request

def file_download(url,file_name):
    urllib.request.urlretrieve(url,file_name)

threads =[]    
for i in range(len(url_list)): 
    t = threading.Thread(target = file_download,args =(url_list[i],data_list[i]))
    t.start()
    threads.append(t)

for thread in threads:
    thread.join()


end = time.perf_counter()

print(f"the program finished in{round(end-start,2)}seconds")


the program finished in0.84seconds


In [ ]:
#use cases:
import time 
import concurrent.futures

start = time.perf_counter()
url_list =[
    'https://pwskills.com/learn/course/data-science-with-generative-ai%20-%202/6891900c886386abb4705279/lesson/68d3c9a0335a87a5c26b2c23/?milestoneId=68ac58db85c44b16e9d24d64&from=%2Flearn%2Fcareer-path%2Fdata-science-with-generative-ai+-+2%2F6891900c886386abb4705279%2Fdashboard%2F%3Ffrom%3D%2Fdashboard%2Foverview&clickText=start_journey&page_from=career_path_page&section=your_track&year=689d8a8892b10554b48b4be7&megaSection=learn&yearName=Self+Paced&sectionId=68d3c9a0335a87a5c26b2ca1&lectureType=video',   
    'https://pwskills.com/learn/course/data-science-with-generative-ai%20-%202/6891900c886386abb4705279/lesson/68d3c9a0335a87a5c26b2c23/?milestoneId=68ac58db85c44b16e9d24d64&from=%2Flearn%2Fcareer-path%2Fdata-science-with-generative-ai+-+2%2F6891900c886386abb4705279%2Fdashboard%2F%3Ffrom%3D%2Fdashboard%2Foverview&clickText=start_journey&page_from=career_path_page&section=your_track&year=689d8a8892b10554b48b4be7&megaSection=learn&yearName=Self+Paced&sectionId=68d3c9a0335a87a5c26b2ca1&lectureType=video',   
    'https://pwskills.com/learn/course/data-science-with-generative-ai%20-%202/6891900c886386abb4705279/lesson/68d3c9a0335a87a5c26b2c23/?milestoneId=68ac58db85c44b16e9d24d64&from=%2Flearn%2Fcareer-path%2Fdata-science-with-generative-ai+-+2%2F6891900c886386abb4705279%2Fdashboard%2F%3Ffrom%3D%2Fdashboard%2Foverview&clickText=start_journey&page_from=career_path_page&section=your_track&year=689d8a8892b10554b48b4be7&megaSection=learn&yearName=Self+Paced&sectionId=68d3c9a0335a87a5c26b2ca1&lectureType=video'  
]
data_list = ["data1.txt","data2.txt","data3.txt"]

import urllib.request

def file_download(url,file_name):
    urllib.request.urlretrieve(url,file_name)
    
    with concurrent.futures.ThreadPoolExecutor()as executor:
        executor.map(file_download,url_list,data_list)
 


end = time.perf_counter()

print(f"the program finished in{round(end-start,2)}seconds")


the program finished in0.0seconds


In [ ]:
# shared variable across all the threads 

start = time.perf_counter()
shared_counter = 0
counter_lock = threading.Lock()

def increment_shared_counter(x):
    global shared_counter
    with counter_lock:
        shared_counter = shared_counter+1
        print(f"Thread{x}:increment shared counter to {shared_counter}")
        time.sleep(1)

threads = [threading.Thread(target=increment_shared_counter,args = (i,))for i in range(10)]
 
for thread in threads:
    thread.start()
for thread in threads :
    thread.join()
    
end = time.perf_counter()
print(f"the program finished in{round(end-start,2)}seconds")


Thread0:increment shared counter to 1
Thread1:increment shared counter to 2
Thread2:increment shared counter to 3
Thread3:increment shared counter to 4
Thread4:increment shared counter to 5
Thread5:increment shared counter to 6
the program finished in6.04seconds


In [ ]:
# shared variable across all the threads 

start = time.perf_counter()
shared_counter = 0
counter_lock = threading.Lock()

def increment_shared_counter(x):
    global shared_counter
    with counter_lock:
        shared_counter = shared_counter+1
        print(f"Thread{x}:increment shared counter to {shared_counter}")
        time.sleep(1)

threads = [threading.Thread(target=increment_shared_counter,args = (i,))for i in range(10)]
 
for thread in threads:
    thread.start()
for thread in threads :
    thread.join()
    
end = time.perf_counter()
print(f"the program finished in{round(end-start,2)}seconds")

Thread0:increment shared counter to 1
Thread1:increment shared counter to 2
Thread2:increment shared counter to 3
Thread3:increment shared counter to 4
Thread4:increment shared counter to 5
Thread5:increment shared counter to 6
Thread6:increment shared counter to 7
Thread7:increment shared counter to 8
Thread8:increment shared counter to 9
Thread9:increment shared counter to 10
the program finished in10.09seconds


In [ ]:
#multiprocessing

def test_func():
    print("do something")
    print("sleep")
    time.sleep(1)
    print("done with sleeping")

p1 = multiprocessing.Process(target=test_func)    
p2 = multiprocessing.Process(target=test_func)

p1.start()
p2.start()

p1.join()
p2.join()



    
test_func()
test_func()
end = time.perf_counter()

print(f"the program finished in{round(end-start,2)}seconds")

do something
sleep
done with sleeping
do something
sleep
done with sleeping
the program finished in2.13seconds


In [ ]:
import multiprocessing
import time
start = time.perf_counter()

def test_func():
    print("do something")
    print("sleep")
    time.sleep(1)
    print("done with sleeping")
    
processes =[]
for i in range(10): 
    p = multiprocessing.Process(target=test_func)
    p.start()
    processes.append(p)

for process in processes :
      process.join()

    
  

end = time.perf_counter()

print(f"the program finished in{round(end-start,2)}seconds")

the program finished in0.28seconds


In [ ]:
#use case 1: 
import multiprocessing
import time
start = time.perf_counter()

def square(index,value):
    value[index] = value[index]**2
    
arr = multiprocessing.Array('i',[1,2,3,4,5,7,6])
    
processes =[]
for i in range(7): 
    p = multiprocessing.Process(target= square,args = (i,arr))
    p.start()
    processes.append(p)

for process in processes :
      process.join()

print(list(arr))
    
  

end = time.perf_counter()

print(f"the program finished in{round(end-start,2)}seconds")

[1, 2, 3, 4, 5, 7, 6]
the program finished in0.33seconds


In [ ]:
import multiprocessing

def enrollement(student_queue):
    for student in ["rahul","rohit","ravi"] :
       student_queue.put(f"enroll request for {student}")
    
def register(student_queue):
    while True :
        enrollment_req = student_queue.get()
        if enrollment_req is None :
            break
        print(f"Register the enrollment request : {enrollment_req}")
        
if True :
    student_queue = multiprocessing.Queue()
    enrollement_process = multiprocessing.Process(target = enrollement , args = (student_queue,))
    registeration_process = multiprocessing.Process(target = register , args = (student_queue,))
    
enrollement_process.start()
registeration_process.start()

enrollement_process.join()
registeration_process.join()





In [ ]:
import multiprocessing

def enrollement(student_queue):
    for student in ["rahul", "rohit", "ravi"]:
        student_queue.put(f"enroll request for {student}")
    
    # Stop signal
    student_queue.put(None)

def register(student_queue):
    while True:
        enrollment_req = student_queue.get()
        if enrollment_req is None:
            break
        print(f"Register the enrollment request: {enrollment_req}")

if __name__ == "__main__":
    student_queue = multiprocessing.Queue()

    enrollement_process = multiprocessing.Process(
        target=enrollement, args=(student_queue,)
    )

    registeration_process = multiprocessing.Process(
        target=register, args=(student_queue,)
    )

    enrollement_process.start()
    registeration_process.start()

    enrollement_process.join()
    registeration_process.join()

#Numpy>>>>>>numerical python

In [5]:
import numpy as np 


In [6]:
print(np.__doc__)


NumPy
=====

Provides
  1. An array object of arbitrary homogeneous items
  2. Fast mathematical operations over arrays
  3. Linear Algebra, Fourier Transforms, Random Number Generation

How to use the documentation
----------------------------
Documentation is available in two forms: docstrings provided
with the code, and a loose standing reference guide, available from
`the NumPy homepage <https://numpy.org>`_.

We recommend exploring the docstrings using
`IPython <https://ipython.org>`_, an advanced Python shell with
TAB-completion and introspection capabilities.  See below for further
instructions.

The docstring examples assume that `numpy` has been imported as ``np``::

  >>> import numpy as np

Code snippets are indicated by three greater-than signs::

  >>> x = 42
  >>> x = x + 1

Use the built-in ``help`` function to view a function's docstring::

  >>> help(np.sort)
  ... # doctest: +SKIP

For some objects, ``np.info(obj)`` may provide additional help.  This is
particularly 

In [ ]:
#with one dimensional array
l=[2,3,4,5,6]
arr=np.array(l)
type(arr)

numpy.ndarray

In [ ]:
a = "prabhat"
print

In [20]:
l_1 =[1,2,3,4,"aj"]
a = np.array(l_1)
type(a)

numpy.ndarray

In [ ]:
a.ndim #returns only one row

1

In [ ]:
#two dimensional array
arr = np.array([[1,2,3],[3,4,5]])
arr

array([[1, 2, 3],
       [3, 4, 5]])

In [29]:
arr.ndim

2

In [ ]:
a = "prabhat"
print(a[::-1])


tahbarp


======MATRIX=======

In [12]:
mat=np.matrix([2,3,4,5])
mat

matrix([[2, 3, 4, 5]])

In [31]:
type(a)

numpy.matrix

In [32]:
a.ndim

2

In [7]:
a1 = np.array([[[1,2],[4,3],[5,6]]])
a1

array([[[1, 2],
        [4, 3],
        [5, 6]]])

In [8]:
a1.ndim

3

In [ ]:
#list - array coversion
l = [1,2,3]
np.asanyarray(l)

array([1, 2, 3])

In [13]:
l[0]

1

In [15]:
l[0]=100
l

[100, 2, 3]

In [ ]:
#shallow copy
arr = l

In [18]:
arr


[100, 2, 3]

In [19]:
l

[100, 2, 3]

In [21]:
#deep copy
b = arr.copy()

In [22]:
b

[100, 2, 3]

In [24]:
b[0]=1000
b

[1000, 2, 3]

In [25]:
arr

[100, 2, 3]

In [ ]:
#approaches to generate an aaray
np.fromfunction(lambda i,j:i==j,(3,3))

array([[ True, False, False],
       [False,  True, False],
       [False, False,  True]])

In [30]:
arr2 = np.fromfunction(lambda i,j:i*j,(3,3))

In [31]:
arr2

array([[0., 0., 0.],
       [0., 1., 2.],
       [0., 2., 4.]])

In [35]:
arr2.shape


(3, 3)

In [34]:
arr2.size

9

In [40]:
#iterable array
import numpy as np

l = [1, 2, 3, 4, 5]
iterator = iter(l)

arr = np.fromiter(iterator,int)

print(arr)
arr

[1 2 3 4 5]


array([1, 2, 3, 4, 5])

 ====== advance numpy =====

In [7]:
import numpy as np

In [2]:
a=np.zeros(5)

In [3]:
a.ndim

1

In [ ]:
a

array([0., 0., 0., 0., 0.])

In [ ]:
np.zeros(10,dtype = int)

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [5]:
b= np.zeros((3,4))
b

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [6]:
b.ndim

2

In [7]:
np.ones(5)

array([1., 1., 1., 1., 1.])

In [8]:
np.ones(5, dtype=int)

array([1, 1, 1, 1, 1])

In [12]:
arr = np.ones((3,4))

In [13]:
arr

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [14]:
arr.ndim

2

In [25]:
#3d array 
r =np.zeros((1,3,4))

In [26]:
r

array([[[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]]])

In [27]:
r.ndim

3

In [42]:
# 4D array
j = np.zeros((1,3,3,4))

In [43]:
j

array([[[[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]],

        [[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]],

        [[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]]]])

In [50]:
a =j+5
a

array([[[[5., 5., 5., 5.],
         [5., 5., 5., 5.],
         [5., 5., 5., 5.]],

        [[5., 5., 5., 5.],
         [5., 5., 5., 5.],
         [5., 5., 5., 5.]],

        [[5., 5., 5., 5.],
         [5., 5., 5., 5.],
         [5., 5., 5., 5.]]]])

In [48]:
a*2

array([[[[10., 10., 10., 10.],
         [10., 10., 10., 10.],
         [10., 10., 10., 10.]],

        [[10., 10., 10., 10.],
         [10., 10., 10., 10.],
         [10., 10., 10., 10.]],

        [[10., 10., 10., 10.],
         [10., 10., 10., 10.],
         [10., 10., 10., 10.]]]])

In [49]:
a-1

array([[[[4., 4., 4., 4.],
         [4., 4., 4., 4.],
         [4., 4., 4., 4.]],

        [[4., 4., 4., 4.],
         [4., 4., 4., 4.],
         [4., 4., 4., 4.]],

        [[4., 4., 4., 4.],
         [4., 4., 4., 4.],
         [4., 4., 4., 4.]]]])

In [ ]:
np.eye(3) #>>>>return 2d array with identity matrix diagonally

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [52]:
np.empty((3,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [2]:
import random
random.choice('aditya')

'y'

In [3]:
random.randrange(1,10)

8

In [4]:
random.random()

0.8752214897213555

In [6]:
random.uniform(7,14)

13.547067050044369

In [8]:
np.array([])

array([], dtype=float64)

In [9]:
np.random.random_sample()

0.7265964840045437

In [11]:

np.random.random_sample((5,))

array([0.45100361, 0.96939163, 0.10568446, 0.68304284, 0.48117955])

In [12]:
np.random.rand(1)

array([0.01764015])

In [13]:
np.random.rand(2,3)

array([[0.86131505, 0.57278702, 0.82384699],
       [0.87681562, 0.21651394, 0.09060672]])

In [15]:
arr = np.random.randint(1,5,size = (3,4))
arr

array([[2, 4, 3, 2],
       [4, 4, 4, 1],
       [2, 2, 4, 2]], dtype=int32)

In [16]:
arr.ndim

2

In [17]:
arr.shape

(3, 4)

In [18]:
arr.size

12

In [19]:
arr

array([[2, 4, 3, 2],
       [4, 4, 4, 1],
       [2, 2, 4, 2]], dtype=int32)

In [20]:
#reshaping
arr.reshape(2,6)

array([[2, 4, 3, 2, 4, 4],
       [4, 1, 2, 2, 4, 2]], dtype=int32)

In [21]:
arr.ndim

2

In [22]:
arr.reshape(4,-4)

array([[2, 4, 3],
       [2, 4, 4],
       [4, 1, 2],
       [2, 4, 2]], dtype=int32)

In [24]:
arr.reshape(12,1)

array([[2],
       [4],
       [3],
       [2],
       [4],
       [4],
       [4],
       [1],
       [2],
       [2],
       [4],
       [2]], dtype=int32)

In [28]:
#base array
arr.reshape(12,1).base

array([[2, 4, 3, 2],
       [4, 4, 4, 1],
       [2, 2, 4, 2]], dtype=int32)

In [29]:
arr.reshape(2,2,3)

array([[[2, 4, 3],
        [2, 4, 4]],

       [[4, 1, 2],
        [2, 4, 2]]], dtype=int32)

In [30]:
arr.reshape(1,2,2,3)

array([[[[2, 4, 3],
         [2, 4, 4]],

        [[4, 1, 2],
         [2, 4, 2]]]], dtype=int32)

In [31]:
arr.reshape(1,2,2,3).ndim

4

==== coditions on array===

In [34]:
import numpy as np

In [38]:
arr_1 = np.random.randint(1,10,(5,6))
arr_1

array([[4, 8, 7, 3, 4, 3],
       [6, 5, 4, 3, 7, 3],
       [6, 5, 5, 9, 1, 5],
       [2, 4, 8, 1, 6, 6],
       [9, 8, 2, 6, 9, 6]], dtype=int32)

In [40]:
arr_1>3

array([[ True,  True,  True, False,  True, False],
       [ True,  True,  True, False,  True, False],
       [ True,  True,  True,  True, False,  True],
       [False,  True,  True, False,  True,  True],
       [ True,  True, False,  True,  True,  True]])

In [41]:
arr_1[0]

array([4, 8, 7, 3, 4, 3], dtype=int32)

In [42]:
arr_1[3][1]

np.int32(4)

In [48]:
arr_1[0:3]

array([[4, 8, 7, 3, 4, 3],
       [6, 5, 4, 3, 7, 3],
       [6, 5, 5, 9, 1, 5]], dtype=int32)

In [46]:
arr_1[0:3,(0,2)]

array([[4, 7],
       [6, 4],
       [6, 5]], dtype=int32)

In [49]:
arr_1[2:5,0:2]

array([[6, 5],
       [2, 4],
       [9, 8]], dtype=int32)

In [55]:
# mathematical operations
arr_3 = np.random.randint(1,3,(3,4))
arr_4 =np.random.randint(1,3,(3,4))

In [56]:
arr_3

array([[1, 2, 1, 1],
       [2, 1, 1, 1],
       [2, 1, 2, 2]], dtype=int32)

In [57]:
arr_4

array([[2, 1, 1, 1],
       [2, 2, 1, 1],
       [2, 2, 1, 1]], dtype=int32)

In [58]:
arr_3+arr_4

array([[3, 3, 2, 2],
       [4, 3, 2, 2],
       [4, 3, 3, 3]], dtype=int32)

In [59]:
arr_3/arr_4

array([[0.5, 2. , 1. , 1. ],
       [1. , 0.5, 1. , 1. ],
       [1. , 0.5, 2. , 2. ]])

In [60]:
arr_3,arr_4

(array([[1, 2, 1, 1],
        [2, 1, 1, 1],
        [2, 1, 2, 2]], dtype=int32),
 array([[2, 1, 1, 1],
        [2, 2, 1, 1],
        [2, 2, 1, 1]], dtype=int32))

In [2]:
import numpy as np

In [5]:
#matirx multiplication
# matrix multiplication
arr_3 = np.random.randint(1,3,(3,4))
arr_4 = np.random.randint(1,3,(4,3))
arr_3 @ arr_4

array([[ 8,  6, 10],
       [11,  9, 14],
       [ 7,  7, 10]], dtype=int32)

In [6]:
np.dot(arr_3,arr_4)

array([[ 8,  6, 10],
       [11,  9, 14],
       [ 7,  7, 10]], dtype=int32)

In [14]:
#broadcasting
a = np.array([[1,2,3,4]])
a

array([[1, 2, 3, 4]])

In [9]:
arr_3

array([[1, 1, 1, 2],
       [1, 2, 2, 2],
       [1, 2, 1, 1]], dtype=int32)

In [10]:
arr_3+a

array([[2, 3, 4, 6],
       [2, 4, 5, 6],
       [2, 4, 4, 5]])

In [11]:
#transpose
a.T

array([1, 2, 3, 4])

In [15]:
a

array([[1, 2, 3, 4]])

In [16]:
a.T

array([[1],
       [2],
       [3],
       [4]])

In [17]:
arr_4.T

array([[1, 1, 2, 2],
       [1, 2, 1, 1],
       [2, 2, 2, 2]], dtype=int32)

==== numpy advance 3 =====

In [38]:
import numpy as np 

In [39]:
arr_1 = np.random.randint(1,3,(3,3))
arr_2 = np.random.randint(1,3,(3,3))


In [40]:
arr_1

array([[1, 2, 2],
       [2, 1, 2],
       [2, 2, 1]], dtype=int32)

In [23]:
arr_2

array([[2, 1, 1],
       [2, 2, 1],
       [2, 1, 1]], dtype=int32)

In [25]:
arr_1.flatten() #2d array collapses into 1d

array([2, 1, 2, 1, 2, 2, 2, 2, 1], dtype=int32)

In [4]:
import numpy as np

In [5]:
arr = np.array([1,2,3,4])
arr

array([1, 2, 3, 4])

In [27]:
arr.ndim

1

In [9]:
np.expand_dims(arr, axis=1)

array([[1],
       [2],
       [3],
       [4]])

In [10]:
np.expand_dims(arr, axis=1).ndim

2

In [14]:
arr = np.zeros((3,4))
arr

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [15]:
np.expand_dims(arr,axis = 0)

array([[[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]]])

In [16]:
np.expand_dims(arr,axis = 0).ndim

3

In [17]:
a = np.array([[1],[3],[2]])
a

array([[1],
       [3],
       [2]])

In [18]:
a.ndim

2

In [20]:
np.squeeze(a)#>>>>>>> remove axes of length one from 'a'

array([1, 3, 2])

In [21]:
np.repeat(a,4)

array([1, 1, 1, 1, 3, 3, 3, 3, 2, 2, 2, 2])

In [23]:
np.repeat(arr,4,axis = 0)

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [28]:
np.repeat(a,4,axis =1)

array([[1, 1, 1, 1],
       [3, 3, 3, 3],
       [2, 2, 2, 2]])

In [29]:
a

array([[1],
       [3],
       [2]])

In [27]:
np.roll(a,-1)

array([[3],
       [2],
       [1]])

In [30]:
np.roll(a,-2)

array([[2],
       [1],
       [3]])

In [32]:
b = np.array([[1,2],[3,4],[2,5],[6,7]])
b

array([[1, 2],
       [3, 4],
       [2, 5],
       [6, 7]])

In [33]:
np.roll(b,-1)

array([[2, 3],
       [4, 2],
       [5, 6],
       [7, 1]])

In [34]:
b

array([[1, 2],
       [3, 4],
       [2, 5],
       [6, 7]])

In [35]:
np.roll(b,2)

array([[6, 7],
       [1, 2],
       [3, 4],
       [2, 5]])

In [ ]:
np.roll(b,2, axis = 0)

array([[2, 5],
       [6, 7],
       [1, 2],
       [3, 4]])

In [41]:
arr_1

array([[1, 2, 2],
       [2, 1, 2],
       [2, 2, 1]], dtype=int32)

In [42]:
arr_2

array([[2, 2, 1],
       [2, 2, 2],
       [2, 1, 1]], dtype=int32)

In [43]:
 arr_2>arr_1

array([[ True, False, False],
       [False,  True, False],
       [False, False, False]])

In [44]:
-arr_1

array([[-1, -2, -2],
       [-2, -1, -2],
       [-2, -2, -1]], dtype=int32)

In [45]:
#numpy string array operations
d = np.array(["aditya","jadhav"])


In [46]:
d

array(['aditya', 'jadhav'], dtype='<U6')

In [47]:
np.char.upper(d)

array(['ADITYA', 'JADHAV'], dtype='<U6')

In [48]:
np.char.lower(d)

array(['aditya', 'jadhav'], dtype='<U6')

In [49]:
np.char.capitalize(d)

array(['Aditya', 'Jadhav'], dtype='<U6')

In [50]:
#mathematical functions
arr_1

array([[1, 2, 2],
       [2, 1, 2],
       [2, 2, 1]], dtype=int32)

In [51]:
np.sin(arr_1)

array([[0.84147098, 0.90929743, 0.90929743],
       [0.90929743, 0.84147098, 0.90929743],
       [0.90929743, 0.90929743, 0.84147098]])

In [53]:
np.cos(arr_1)

array([[ 0.54030231, -0.41614684, -0.41614684],
       [-0.41614684,  0.54030231, -0.41614684],
       [-0.41614684, -0.41614684,  0.54030231]])

In [54]:
np.log10(arr_1)

array([[0.     , 0.30103, 0.30103],
       [0.30103, 0.     , 0.30103],
       [0.30103, 0.30103, 0.     ]])

In [55]:
np.exp(arr_1)

array([[2.71828183, 7.3890561 , 7.3890561 ],
       [7.3890561 , 2.71828183, 7.3890561 ],
       [7.3890561 , 7.3890561 , 2.71828183]])

In [56]:
np.power(arr_1,3)

array([[1, 8, 8],
       [8, 1, 8],
       [8, 8, 1]], dtype=int32)

In [66]:
np.max(arr_1)

np.int32(2)

In [67]:
arr_2

array([[2, 2, 1],
       [2, 2, 2],
       [2, 1, 1]], dtype=int32)

In [59]:
np.mean(arr_2)

np.float64(1.6666666666666667)

In [60]:
np.std(arr_2)

np.float64(0.4714045207910317)

In [64]:
np.median(arr_2)

np.float64(2.0)

In [69]:
np.multiply(arr_1,arr_2)

array([[2, 4, 2],
       [4, 2, 4],
       [4, 2, 1]], dtype=int32)

In [ ]:
np.mod(arr_1,arr_2)#element wise remainder

array([[1, 0, 0],
       [0, 1, 0],
       [0, 0, 0]], dtype=int32)

In [72]:
np.sqrt(arr_1)

array([[1.        , 1.41421356, 1.41421356],
       [1.41421356, 1.        , 1.41421356],
       [1.41421356, 1.41421356, 1.        ]])

In [73]:
# sorting and searching
e = np.array([5,6,3,10])
e

array([ 5,  6,  3, 10])

In [74]:
np.sort(e)


array([ 3,  5,  6, 10])

In [75]:
d = np.array([5,60,3,10])
d

array([ 5, 60,  3, 10])

In [76]:
np.sort(d)

array([ 3,  5, 10, 60])

In [77]:
np.searchsorted(d,9)

np.int64(3)

In [78]:
f = np.array([5,60,3,10,500,20,100,1000])
f

array([   5,   60,    3,   10,  500,   20,  100, 1000])

In [80]:
np.count_nonzero(f)

np.int64(8)

In [82]:
f>100000

array([False, False, False, False, False, False, False, False])

In [84]:
np.where(f>0)

(array([0, 1, 2, 3, 4, 5, 6, 7]),)

In [85]:
np.extract(f>0,f)

array([   5,   60,    3,   10,  500,   20,  100, 1000])

In [86]:
f

array([   5,   60,    3,   10,  500,   20,  100, 1000])

In [87]:
f.byteswap()# swap the bytes of array elements

array([  360287970189639680,  4323455642275676160,   216172782113783808,
         720575940379279360,  -864409653478424576,  1441151880758558720,
        7205759403792793600, -1728537831980138496])

==== matlib with numpy ===

In [88]:
import numpy.matlib as nm

In [90]:
nm.zeros(5)

matrix([[0., 0., 0., 0., 0.]])

In [91]:
nm.ones((3,4))

matrix([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

===== Pandas =====

In [2]:
import pandas as pd